spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yakimbee
    username: root
    password: P@$$w0rd@2292
  jpa:
    hibernate:
      ddl-auto: update



    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



